
<?php

    session_start();

    include "./incs/header.php";
    include "./incs/navbar.php";
?>
<div class="container" dir="ltr">
    <strong>Privacy Policy</strong> <p>
        Sarhne Inc, built the sarhne app and
        www.sarhne.com website .
    </p> <p>
        This page is used to inform visitors regarding our
        policies with the collection, use, and disclosure of Personal
        Information if anyone decided to use our Service.
    </p> <p>
        If you choose to use our Service, then you agree to
        the collection and use of information in relation to this
        policy. The Personal Information that we collect is
        used for providing and improving the Service. We will not use or share your information with
        anyone except as described in this Privacy Policy.
    </p> <p>
        The terms used in this Privacy Policy have the same meanings
        as in our Terms and Conditions, which is accessible at
        sarhne unless otherwise defined in this Privacy Policy.
    </p> <p><strong>Information Collection and Use</strong></p> <p>
        For a better experience, while using our Service, we
        may require you to provide us with certain personally
        identifiable information. The information that
        we request will be retained by us and used as described in this privacy policy.
    </p> <div><p>
        The app does use third party services that may collect
        information used to identify you.
    </p> <p>
        Link to privacy policy of third party service providers used
        by the app
    </p>
        <ul>
            <li><a href="https://www.facebook.com/about/privacy" target="_blank" rel="noopener noreferrer">Facebook </a></li>
        <li><a href="https://www.google.com/policies/privacy/" target="_blank" rel="noopener noreferrer">Google Play Services</a></li>
            <!---->
            <li><a href="https://firebase.google.com/policies/analytics" target="_blank" rel="noopener noreferrer">Google Analytics for Firebase</a></li>
            <li><a href="https://firebase.google.com/support/privacy/" target="_blank" rel="noopener noreferrer">Firebase Crashlytics</a></li>
            <li><a href="https://admob.com/" target="_blank" rel="noopener noreferrer">admob.com</a></li>
            <li><a href="https://onesignal.com/tos" target="_blank" rel="noopener noreferrer"> OneSignal Messaging SDK</a></li>
            <li><a href="https://gdpr-info.eu/" target="_blank" rel="noopener noreferrer">Data Privacy Protection Act GDPR </a></li>
        
            <!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----></ul></div>


    <h2>1. The Information We collect</h2>
    
    <p style="background: #ffe5a9;
    padding: 10px;">
    Important note: When you delete your account if it is linked to information from Facebook such as logins, this data is deleted immediately and we will not keep it.
    </p> 
    

    <p>We will collect information provided by you during the use of the Software or information generated by the use of the Software in accordance with the following ways.</p>

    <p><strong>Information that you submit</strong></p>

    <p>We collect information that you provide directly to us, including when you register for an account, provide feedback about the App, or contact us with questions or comments about the App.</p>

    <p>1) Registration Information</p>

    <p>For getting more chances to interact with other users, you may voluntarily to create an account. When you register the account(&quot;Account&quot;) with your mobile phone number, we will collect your mobile phone number, username, gender identity, age, preference, personal introduction and profile pictures(&quot;Registration Information&quot;) to the Software in order to assist you with completing registration and to protect your Account. For such profile pictures, Only with your consent, will we gain access to your camera or album to collect them.</p>

    <p>2) Support Related Information</p>

    <p>If you communicate with us via our support section or via email, we may also collect your email address, name and any information you voluntarily submitted to us in connection with such support (for example, your name, company name, and particular support query or request).</p>

    <p>3) Microphone</p>

    <p>For communicating in the chat room, you may voluntarily to grant us the permission to access to the microphone in your mobile device.</p>

    <p>4) Notifications</p>

    <p>If you voluntarily to allow us to send notification to you, we will notify you when there are certain important announcements.</p>

    <p><strong>Information that is processed automatically</strong></p>

    <p>1) Information of the third-party account.</p>

    <p>You may choose to log in the App through the third-party account, which is including but not limited to Google, Facebook, and when you do , we will collect your display name, social media avatars, gender identity, age and other information of your third-party account.</p>

    <p>2) Device Information.</p>

    <p>
        Location Information. We infer your general location information (for example, your IP address may indicate your general geographic region).
    </p>

    <p>When you use the Software, we will collect certain information about your mobile device, such as model, operating system, unique device identifier, ISP (Internet Service Provider), version of the Software, access network mode, type and status, the quality of your network, country, location, language and Android ID.</p>

    <p>3) Usage Information.</p>

    <p>Certain usage related information regarding your use and interaction with your device and the Software, such as when and how you use the Software, how frequently you use them, your operation log and service log information.</p>

    <p>4) Payment data.</p>

    <p>We may collect certain information about your top-up orders and payment records of virtual gifts purchased with virtual coins. such as purchase items, payment time, order status. We do not collect and we are not responsible for the collection or security of payment details. Payment information is processed and stored using third-party companies (such as Google). These companies can be contacted through their websites. Before entering your personal details, we suggest that you read and become familiar with the privacy policy of these third-party companies.</p>

    <p>5) Virtual coins and gifts.</p>

    <p>We may collect certain information about virtual coins and gifts in your Account, such as the growth/ consumption of your virtual coins, the recipient, giving time, type, and quantity of the virtual gifts which you give to other users through the Sofware.</p>

    <h2>2. Use of your information</h2>

    <p>Our main goal is to ensure your experience on the App is an enjoyable one. In order to deliver an enjoyable experience to you, we may use your Registration and other information to:</p>

    <p>a. offer you our services and features;</p>

    <p>b. personalize the App and the content we deliver to you;</p>

    <p>c. resolve disputes between you and other Users; and</p>

    <p>d. investigate fraud, protect our legal rights, and to enforce our Terms of service.</p>

    <h2>3. Disclosure of Your Information</h2>

    <p>We will not disclose your information, except in the limited circumstances described here:</p>

    <p>1) Your Consent – Where you voluntarily do upload and choose to provide your personal information on your profile when you create an Account, you are explicitly consenting to our processing of your information and making this public to other users. Therefore, we recommend you to think carefully about the information you disclose about yourself. And if you do not want to disclose any of your personal information, you can withdraw this consent at any time via Settings or Profile in the App.</p>

    <p>2) Service Providers - We engage certain trusted third parties to perform functions and provide services to us. We may share your personal information with these third parties, but only for the purposes of performing these functions and providing such services, e.g. information technology companies (hardware and software) which provide services to support the Software.</p>

    <p>3) Required by law- If we are required by law to disclose your information, we may share your information with law enforcement or other competent authorities and any third party, as may be required (e.g., to detect, prevent or otherwise address fraud, security, or technical issues; to respond to claims or satisfy any legal process, subpoena, or governmental request; or to protect the rights, property, or personal safety of the other users, our partners, or the general public).</p>

    <p>4) Business Transfers -In the event that we or any of our affiliates undergoes a business transition or change of ownership, such as a merger, acquisition by another company, re-organization, or sale of all or a portion of its assets, or in the event of insolvency or administration, we may be required to disclose your personal information.</p>

    <p>5) Aggregated Information – We may share aggregated information with third parties that includes your personal information (but which doesn’t identify you directly) together with other information including log data for industry analysis and demographic profiling. You may opt-out of receiving marketing messages by using the opt-out mechanisms and links provided in each email.</p>

    <p>We ensure these parties must adhere to strict data protection and confidentiality provisions that are consistent with this Privacy Policy. Measures are taken to ensure that the data shared is non-attributable to the greatest extent possible.</p>

    <h2>4. Modifying Your Registration Information</h2>

    <p>You may access or modify the Registration Information you provided. When your Account is deactivated, we take reasonable efforts to make sure it is no longer viewable on the App. We are not responsible for any information, pictures, comments, or other content that is deleted from our systems resulting from the deactivation of your Account.</p>

    <p><strong>Warning: </strong>Even after you remove information from your profile or delete your Account, copies of that information may still be viewable and/or accessed to the extent such information has been previously shared with others, or copied or stored by other users or to the extent such information has been shared with search engines. We cannot control this, nor do we accept any liability for this. If you have given third party applications or websites access to your personal information they may retain such information to the extent permitted under their terms of service or privacy policies.</p>





    <p><strong>Log Data</strong></p> <p>
        We want to inform you that whenever you
        use our Service, in a case of an error in the app
        we collect data and information (through third party
        products) on your phone called Log Data. This Log Data may
        include information such as your device Internet Protocol
        (“IP”) address, device name, operating system version, the
        configuration of the app when utilizing our Service,
        the time and date of your use of the Service, and other
        statistics.
    </p> <p><strong>Cookies</strong></p> <p>
        Cookies are files with a small amount of data that are
        commonly used as anonymous unique identifiers. These are sent
        to your browser from the websites that you visit and are
        stored on your device's internal memory.
    </p> <p>
        This Service does not use these “cookies” explicitly. However,
        the app may use third party code and libraries that use
        “cookies” to collect information and improve their services.
        You have the option to either accept or refuse these cookies
        and know when a cookie is being sent to your device. If you
        choose to refuse our cookies, you may not be able to use some
        portions of this Service.
    </p> <p><strong>Service Providers</strong></p> <p>
        We may employ third-party companies and
        individuals due to the following reasons:
    </p> <ul><li>To facilitate our Service;</li> <li>To provide the Service on our behalf;</li> <li>To perform Service-related services; or</li> <li>To assist us in analyzing how our Service is used.</li></ul> <p>
        We want to inform users of this Service
        that these third parties have access to your Personal
        Information. The reason is to perform the tasks assigned to
        them on our behalf. However, they are obligated not to
        disclose or use the information for any other purpose.
    </p> <p><strong>Security</strong></p> <p>
        We value your trust in providing us your
        Personal Information, thus we are striving to use commercially
        acceptable means of protecting it. But remember that no method
        of transmission over the internet, or method of electronic
        storage is 100% secure and reliable, and we cannot
        guarantee its absolute security.
    </p> <p><strong>Links to Other Sites</strong></p> <p>
        This Service may contain links to other sites. If you click on
        a third-party link, you will be directed to that site. Note
        that these external sites are not operated by us.
        Therefore, we strongly advise you to review the
        Privacy Policy of these websites. We have
        no control over and assume no responsibility for the content,
        privacy policies, or practices of any third-party sites or
        services.
    </p> <p><strong>Children’s Privacy</strong></p> <p>
        These Services do not address anyone under the age of 13.
        We do not knowingly collect personally
        identifiable information from children under 13. In the case
        we discover that a child under 13 has provided
        us with personal information, we immediately
        delete this from our servers. If you are a parent or guardian
        and you are aware that your child has provided us with
        personal information, please contact us so that
        we will be able to do necessary actions.
    </p> <p><strong>Changes to This Privacy Policy</strong></p> <p>
        We may update our Privacy Policy from
        time to time. Thus, you are advised to review this page
        periodically for any changes. We will
        notify you of any changes by posting the new Privacy Policy on
        this page.
    </p> <p>This policy is effective as of 2021-07-12</p> <p><strong>Contact Us</strong></p> <p>
        If you have any questions or suggestions about our
        Privacy Policy, do not hesitate to contact us at sarhne.com@gmail.com
    </p>   <script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194" integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==" data-cf-beacon='{"rayId":"72ba4577def2733f","token":"218cd1753fe64a258e6d9b2b19630e7e","version":"2022.6.0","si":100}' crossorigin="anonymous"></script>


</div>
<?php

    include "./incs/footer.php";
?>
